[package]
name = "rucksack"
version = "0.0.0"
license = "Apache-2.0"
authors = ["Duncan McGreggor <oubiwann@gmail.com>"]
repository = "https://github.com/oxur/rucksack"
documentation = "https://docs.rs/rucksack/"
categories = ["command-line-interface"]
keywords = ["password-manager", "terminal"]
exclude = ["/.github", "/resources", ".gitignore"]
edition = "2021"

[lib]
name = "rucksack"

[dependencies]
anyhow = "1.0"
chacha20poly1305 = { version = "0.10.1", features = ["stream"] }
rand = "0.8"
tui = "0.19.0"
