[package]
name = "rucksack-db"
description = "The rucksack encrypted database"
version = "0.11.0"
license = "Apache-2.0"
authors = ["Duncan McGreggor <oubiwann@gmail.com>"]
repository = "https://github.com/oxur/rucksack"
documentation = "https://docs.rs/rucksack-db/"
categories = ["database-implementations"]
keywords = ["password-manager", "terminal"]
exclude = ["/.github", ".gitignore"]
edition = "2021"

[lib]
name = "rucksack_db"

[features]
default = ["filesystem"]
filesystem = ["dep:dashmap"]
redb = ["dep:redb"]

[dependencies]
aead = "0.5"
aes-gcm = "0.10"
anyhow = "1.0"
bincode = "2.0.1"
cfg-if = "1.0.4"
chrono = { version = "0.4", default-features = false, features = ["serde"] }
crc32fast = "1.5"
csv = "1.4"
dashmap = { version = "5.5.3", features = ["serde"], optional = true }
enum-iterator = "1.5.0"
heck = "0.4.1"
log = { version = "0.4", features = ["kv"] }
rand = "0.8"
redb = { version = "1.5", optional = true }
secrecy = "0.8"
serde = { version = "1.0", features = ["derive"] }
tempfile = { version = "3", default-features = false }
url = "2.5"
uuid = { version = "1.19", features = ["v4"] }
versions = "6.3.2"

[dependencies.rucksack-lib]
path = "../rucksack-lib"
version = "0.10"
